### ISSUE TITLE
Multiple providers not working

### ISSUE THREAD

**Issue by jchasey** [nalipaz/hassio-addons#1]
If you provide multiple providers then only the last one appears to be set, I have a couple of DDNS entries and 'lost' the first one in that the IP didn't appear to be updated. Swapped the order of the configuration and it was then updated fine. Therefore I suspect only the last entry is getting actioned.

**Comment by slackbits** [comment]
Just name your provider <provider>:1, <provider>:2, etc.  

For example:
```javascript
{
  "providers": [
    {
      "provider": "default@domains.google.com:1",
      "username": "<USER>",
      "password": "<PASS>",
      "hostname": "first-host.example.com"
    },
    {
      "provider": "default@domains.google.com:2",
      "username": "<USER>",
      "password": "<PASS>",
      "hostname": "host2.example.com"
    },
    {
      "provider": "default@domains.google.com:3",
      "username": "<USER>",
      "password": "<PASS>",
      "hostname": "third-host.example.com"
    }
  ]
}
```

I too had the issue and found it in the example config at https://github.com/troglobit/inadyn. 

(Edited to format code block )

**Comment by nalipaz** [comment]
Thanks for helping out @slackbits, I was pressed for time to check up on this. I did think that I had tested that so was pretty sure it should work. Glad to here you knew how to use it.
