### ISSUE TITLE
IPV6 doesn't seem to be opperational

### ISSUE THREAD

**Issue by rbray89** [nalipaz/hassio-addons#2]
I have a global permanent IPv6 Address on the host, and the address doesn't seem to be detected or forwarded to my DDNS provider.

This is on a HassOS device.

**Comment by nalipaz** [comment]
This is merely a wrapper around inadyn so I would guess this is more likely an issue with config or the inadyn service specifically and not this particular addon. I suggest researching your issue in relation to inadyn specifically.
