### ISSUE TITLE
required key not provided @ data['arch']. Got None

### ISSUE THREAD

**Issue by ronsum232** [nalipaz/hassio-addons#3]
Hassio System log:

WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/85933338/inadyn/config.json: required key not provided @ data['arch']. Got None

**Comment by ronsum232** [comment]
I was able to install as a local addon, having added to the config.json.

**Comment by nalipaz** [comment]
So were you able to resolve this?

**Comment by ronsum232** [comment]
I've been using as a local addon... let me try and I'll report back.

**Comment by ronsum232** [comment]
Still receiving in Hassio system log:
`19-04-24 19:47:51 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/85933338/inadyn/config.json: required key not provided @ data['arch']. Got None`

**Comment by ronsum232** [comment]
Also, to install as a local addon, I inserted the following at line 8 of the config.json:
`  "arch": [
    "aarch64",
    "amd64",
    "armhf",
    "i386"
  ],`

**Comment by kylerm42** [comment]
I'm also getting the error and unable to use this add-on. When can we expect to merge PR #4?

**Comment by ronsum232** [comment]
bump

**Comment by mora-phi** [comment]
Same here, unable to install the addon due to the same error after adding the repository.

**Comment by deku-m** [comment]
Like to see this updated again good add-on when you use your own domain for hass.

For above if you clone the repo you can change the config file and add the mentioned fix:
After that you can use your repo link in hass as store add-on.

> Also, to install as a local addon, I inserted the following at line 8 of the config.json:
> ` "arch": [ "aarch64", "amd64", "armhf", "i386" ],`

**Comment by nalipaz** [comment]
I am glad to accept a Pull requests to fix these things, but I just don't have time to devote to working on this at the moment. I have pulled in #4 .

**Comment by mora-phi** [comment]
Great thanks, installed now without a hiccup.

**Comment by ronsum232** [comment]
Many thanks... much preferred to installing locally. Wish I knew enough to offer a PR myself. This is a really important tool in my HA setup and you've done us a great service.
